### ISSUE TITLE
In Eclipse IDE + LSP4MP 0.6, clicking on quick fixes does nothing (the code change is not executed)

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4mp#362]
## Environment

I tried in two environments, both on top of 2022-12 (4.26) "..for Java Developers" package.

1.  installing Quarkus Tools:
>  Quarkus Tools	1.9.0.v20221212-0953	org.jboss.tools.quarkus.feature.feature.group	null
2. doing a development build of Liberty Tools Eclipse (the version we have in the Eclipse Marketplace uses LSP4MP v0.5.0).

The LSP4MP is activated through a Liberty Maven project via dependency:
```xml
        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>3.3</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
```

## Problem

In each env,  I got the same result for these two MP Health-related scenarios:

I got a warning, and when I hovered over the warning, I got a dialog box with a link for a quick fix.  However, when I clicked on the link, the dialog box disappears, but there is no change to the code.

In the first case I have the annotation but w/o implementing the interface.  In the 2nd case I have the opposite, I implement the interface but w/o the annotation.

![image](https://user-images.githubusercontent.com/4081634/220421398-79a1bc04-0591-42ba-a4c9-6e6b7d6dcc47.png)
![image](https://user-images.githubusercontent.com/4081634/220421761-12b85bb1-9374-4af7-b19f-fe544e28870f.png)

**Comment by scottkurz** [comment]
Noticing that there was a fairly-recent change specific to health quick fix (https://github.com/eclipse/lsp4mp/pull/316/files) I checked to see if there were other examples.

I managed to exercise the **ApplicationScopedAnnotationMissingQuickFix** by adding `@RequestScoped` to a class with a metric.  

The net result was the same, I got a warning, and by hovering got a Quick Fix to click (to change to `@ApplicationScoped`), but clicking on it did not change the source.

**Comment by scottkurz** [comment]
Looking at the history, it seems like https://github.com/eclipse/lsp4mp/pull/299 could possibly be related??   But that's just my naive take, I don't know the code enough to know what I'm talking about.

**Comment by angelozerr** [comment]
I suspect the problem comes from LSP4E https://github.com/eclipse/lsp4e/issues/337 which doesn't support correctly codeaction resolve. This issue has been fixed.

**Comment by scottkurz** [comment]
@angelozerr thank you for taking a look.

I made an attempt at trying the latest LSP4E code.    It still doesn't work, though I'm not sure it proves anything one way or another given where the 1Q23 release stands at the moment.

I took my 4.26 Eclipse and pointed it to the lsp4e snapshot repo which installed: 
>  Language Server Protocol client for Eclipse IDE (Incubation)	0.16.0.202302211601	org.eclipse.lsp4e	Eclipse.org

After doing this I see a different problem behavior:  I don't have a "quick fix" at all.. just a diagnostic:
![image](https://user-images.githubusercontent.com/4081634/220454651-e7abd9ea-2166-4af3-905e-df6c18f88670.png)

Perhaps this isn't a useful environment without other content targeted for the 4.27 release?   Not sure.

(I also did an install of the 4.27 M2 milestone but the lsp4e version is still  0.15.0.202211292024 which is before the PR you mentioned, so that doesn't tell us anything).

Perhaps we have to wait longer to test but I mention that in case you have any thoughts in the meantime.  Thank you.

**Comment by angelozerr** [comment]
I think the problem comes from LSP4E. @datho7561 or @JessicaJHee  ould you check it is working on vscode please.

@scottkurz even if I think it is an issue from LSP4E I suggest you that you create an issue at https://github.com/jbosstools/jbosstools-quarkus to keep trace

**Comment by datho7561** [comment]
It works for me in VS Code. Maybe it's something related to the code action resolve support, but this is just speculation

**Comment by datho7561** [comment]
I'll double check 0.6.0 as well though, since that's the version that Scott's using

**Comment by scottkurz** [comment]
When I try with Quarkus Tools 4.26.0 plus the  lsp4e 0.16.0.202302211601, on top of 4.26 it's even worse.

I get a "Problem" in the Problems view but no pop-up Diagnostic nor a Quick Fix.

![image](https://user-images.githubusercontent.com/4081634/220662109-e34cd00c-220a-4812-ae87-7c88c5ccb3aa.png)

(It was with LSP4MP 0.6 brought in via a dev build of Liberty Tools Eclipse that I got the symptom in : https://github.com/eclipse/lsp4mp/issues/362#issuecomment-1439096521)

I'm not going to open an issue on Quarkus Tools for now... this is probably considered an unsupported environment so I don't want to confuse anyone there.     

It does seem like a top priority to test once the later 4.27 drivers become available though.

**Comment by angelozerr** [comment]
I'm pretty sure the problem comes from LSP4E. It is a client problem since vscode is working (according to @datho7561 comment).

**Comment by scottkurz** [comment]
> I'm pretty sure the problem comes from LSP4E. It is a client problem since vscode is working (according to @datho7561 comment).

OK, I was a bit hesitant because of all the parts still under development for this quarter, but I guess I can just open the LSP4E issue, dump my installation details and see what people think over there.   Thank you.

**Comment by angelozerr** [comment]
@scottkurz please create an issue on JBoss Quarkus tools. I think it misses the resolve code action part.

**Comment by angelozerr** [comment]
When you click on code action it should consume the resolveCodeAction of LSP4MP. https://github.com/jbosstools/jbosstools-quarkus/blob/d056fff871ec580a2ba8a99254645e1d79215779/plugins/org.jboss.tools.quarkus.lsp4e/src/org/jboss/tools/quarkus/lsp4e/QuarkusLanguageClient.java#L220 doesn't implement resolveCodeAction. I think it is your original issue.
I suggest that you create in jbosstools-quarkus an issue for that.

But by using last version of LSP4E none code actions appears, it is an LSP4E issue, I suggest that you create in LSP4E  an issue for that.

**Comment by angelozerr** [comment]
@scottkurz after debugging all plugins (LSP4E, LSP4MP, JBoss Quarkus), I can confirm that the problem comes from JBoss Quarkus.

I created a PR https://github.com/jbosstools/jbosstools-quarkus/pull/208 to fix the issue.

Thanks again for your helpful informations and your patience.

**Comment by angelozerr** [comment]
I close this issue since it is an issue for Jboss Quarkus Tools https://github.com/jbosstools/jbosstools-quarkus/pull/208
//cc @sbouchet
